import DeviceSingleOperation as op


def upper_filter_vial_grab(worker_id, process_data):
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 1, 100)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 2, 10)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 51, 100)
    process_data[str(len(process_data) + 1)] = op.robot_efg(worker_id, 13)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 52, 20)
    process_data[str(len(process_data) + 1)] = op.robot_efg(worker_id, 17)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 51, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 5, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 53, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 54, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 55, 5)
    process_data[str(len(process_data) + 1)] = op.robot_efg(worker_id, 8)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 54, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 53, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 5, 50)
    process_data[str(len(process_data) + 1)] = op.motor(5, 'block6')
    process_data[str(len(process_data) + 1)] = op.motor(5, 'block5')
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 56, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 57, 10)
    process_data[str(len(process_data) + 1)] = op.robot_efg(worker_id, 17)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 54, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 53, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 5, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 58, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 59, 50)
    process_data[str(len(process_data) + 1)] = op.robot_efg(worker_id, 13)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 58, 50)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 1, 100)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 2, 10)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 9, 100)
    process_data[str(len(process_data) + 1)] = op.robot_efg(worker_id, 0)
    process_data[str(len(process_data) + 1)] = op.robot(worker_id, 60, 10)
    return process_data
